source 'https://rubygems.org'

gem 'eks-cent', '4.0.0'
gem 'eksa-server'
gem 'sequel'
gem 'sqlite3'
gem 'bcrypt'
gem 'dotenv'
gem 'cloudinary'
gem 'mongo'
gem 'mysql2'
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'mail'
gem 'minitest'
